#ifndef rcl57mcu_h
#define rcl57mcu_h

#define SYSTICK_PERIOD_US (50)
#define DISPLAY_PERIOD_US (6400)
#define SEGMENT_PERIOD_US (DISPLAY_PERIOD_US / 8)
#define SEGMENT_TICKS (SEGMENT_PERIOD_US / SYSTICK_PERIOD_US)
#define SYSTICK_TIMER_FREQ (1000000 / SYSTICK_PERIOD_US)

#define IDLE_DISP_CYCLE_TIMEOUT (4000)
#define IDLE_SYSTICK_PERIOD_US (10000)
#define IDLE_SYSTICK_TIMER_FREQ (1000000 / IDLE_SYSTICK_PERIOD_US)
#define PSAVE_IDLE_MS (5000)
#define PSAVE_IDLE_TICKS (PSAVE_IDLE_MS * 1000 / IDLE_SYSTICK_PERIOD_US)
#define PSAVE_BLINK_MS (250)
#define PSAVE_BLINK_TICKS (PSAVE_BLINK_MS * 1000 / DISPLAY_PERIOD_US)

#endif /* rcl57mcu_h */



